### ISSUE TITLE
Using new EAM hessian in narrow periodic cell

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#38]
I'm keen to try out the new EAM Hessian functionality - thanks @wgnoehring for contributing this!

I'd like to apply to a system which is large in 2 dimension but narrow in the 3rd dimension, and  I see the comment [here](https://github.com/libAtoms/matscipy/blob/master/matscipy/calculators/eam/calculator.py#L360) requires i-j pairs to be unique.

Is there a fundamental reason why this is restricted to systems larger than cutoff in all dimensions? Couldn't we label matrix element by `(i, j, shift)` rather than just `(i, j)`?

**Comment by wgnoehring** [comment]
I think this problem is related to #34. The EAM calculator requires a method that, given a pair `ij`, finds the location of the reversed pair `ji` in the neighbor list. My first implementation did not properly handle cases where pairs `ij` were in the neighbor list multiple times with different distance, due to small system size. This may have been the reason why I observed asymmetric Hessians and thus
required a minimum system size. Since the method has been fixed, I think this constraint can be
removed. I just have to check whether `term_8` is still constructed properly.
